### ISSUE TITLE
Expose util functions

### ISSUE THREAD

**Issue by nixon-voxell** [linebender/vello_svg#11]
Right now, a lot of the useful functions in vello_svg is locked up inside a private util mod:
```rust
pub fn to_affine(ts: &usvg::Transform) -> Affine
pub fn to_stroke(stroke: &usvg::Stroke) -> Stroke
pub fn to_bez_path(path: &usvg::Path) -> BezPath
pub fn into_image(image: image::ImageBuffer<image::Rgba<u8>, Vec<u8>>) -> Image
pub fn to_brush(paint: &usvg::Paint, opacity: usvg::Opacity) -> Option<(Brush, Affine)>
pub fn decode_raw_raster_image(
    img: &usvg::ImageKind,
) -> Result<image::RgbaImage, image::ImageError>
```

As a user from the outside, it would be nice if I can access these functions and use it to transform an Svg into custom data struct that uses `Vello` types other than just `Scene` (maybe a collection of `BezPath`s).

**Comment by simbleau** [comment]
Sounds perfectly reasonable, we should make these public - agreed.
