### ISSUE TITLE
How about flatten the text path with usvg?

### ISSUE THREAD

**Issue by mhfan** [linebender/vello_svg#16]
https://github.com/linebender/vello_svg/blob/cf6fe5502e1b6701a1dd4e8dc20f706a49d6a47c/src/lib.rs#L262-L264

Similarly as:

https://github.com/RazrFalcon/resvg/blob/ac7e7d0c40eb22dae19139f36ce28ad16e123db4/crates/resvg/src/render.rs#L45

**Comment by simbleau** [comment]
This isn't implemented yet, but is on the TODO list. :)
