### ISSUE TITLE
Should the image `view_box_transform` actually be `view_box.to_transform(image_size)`?

### ISSUE THREAD

**Issue by mhfan** [linebender/vello_svg#17]
https://github.com/linebender/vello_svg/blob/cf6fe5502e1b6701a1dd4e8dc20f706a49d6a47c/src/lib.rs#L217-L237

**Comment by simbleau** [comment]
Thanks for the issue! I'll take a look shortly.

**Comment by simbleau** [comment]
viewbox transforms were removed in usvg 0.42, which I just updated to, and is pending merge in #18 :)
